name: FPL Notify

on:
  schedule:
    - cron: "*/5 * * * *"   # รันทุก 5 นาที
  workflow_dispatch: {}      # กดรันมือได้

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TIMEZONE_OFFSET_HOURS: "7"
      NOTIFY_OFFSET_SECONDS: "3600"   # แจ้งล่วงหน้า 1 ชม (ปรับได้)
      WINDOW_MINUTES: "5"             # หน้าต่าง 5 นาที
      MODE: "window"
      MENTION_EVERYONE: "true"
      MENTION_TARGET: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python sent_noti.py
